name: Manual Debug build
on:
  workflow_dispatch:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Clone Project Into Ubuntu
        run: |
          echo "The job was Manually triggered."
          echo "This job is running on a ${{ runner.os }} server hosted by GitHub!"
        uses: actions/checkout@v3
          echo "The ${{ github.repository }} repository has been cloned."

      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
          cache: gradle

      - run: echo "The workflow is now ready to test your code."
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
      - name: Build Debug build
        run: | 
            ./gradlew build
            echo "Build status report=${{ job.status }}."
