# Workflow Name
name: Manual Debug build

#Events
on:
  workflow_dispatch: #used to make this workflow run manually.

jobs:
  build_debug_build:
    name: debug build
    runs-on: ubuntu-latest

    steps:
      - name: Clone project
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'
          cache: gradle

      - name: Gradlew permission
        run: chmod +x ./gradlew

      - name: Build Debug build with Gradle
        run: ./gradlew build

      - name: Build Release APK
        id: create_release
        run: ./gradlew assembleRelease --no-daemon

      - name: Sign APK
        env:
          ENCODED_KEYSTORE: ${{ secrets.KEY_STORE_64 }}
          DECODED_KEYSTORE_PATH: ${{ secrets.KEY_STORE_PATH }}
        run: |
            echo $ENCODED_KEYSTORE > keystore_base64.txt
            base64 -d keystore_base64.txt > DECODED_KEYSTORE_PATH
