# Workflow Name
name: Manual Debug build

#Events
on:
  workflow_dispatch: #used to make this workflow run manually.

jobs:

  build_debug_build:
    name: debug build
    runs-on: ubuntu-latest
    steps:
      - name: Clone project
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
          cache: gradle

      - name: Gradlew permission
        run: chmod +x ./gradlew

      - name: Build Debug build with Gradle
        run: ./gradlew build
        with:
          name: debug-apk
          path: '**/app/'
