# Workflow Name
name: Manual Debug build

#Events
on:
  push:
    branch: main

  workflow_dispatch: #used to make this workflow run manually.

jobs:
  build_debug_build:
    name: debug build
    runs-on: ubuntu-latest

    steps:
      - name: Clone project
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'
          cache: gradle

      - name: Gradlew permission
        run: chmod +x ./gradlew

      - name: Decode keystore
        uses: RollyPeres/base64-to-path@v1
        with:
          filePath: ${{ github.workspace }}/releaseKeyStore.jks
          encodedString: ${{ secrets.KEY_STORE_64 }}


#      - name: Build Signed Release APK
#        env:
#          RELEASE_KEYSTORE_PATH: ${{ github.workspace }}/releaseKeyStore.jks
#          RELEASE_SIGNING_PASSWORD: ${{ secrets.KEY_STORE_PASS }}
#          RELEASE_SIGNING_USERNAME: ${{ secrets.KEY_STORE_PASS }}
#          RELEASE_SIGNING_ALIAS: ${{ secrets.KEY_STORE_ALISE }}
#        run: |
#            ./gradlew assembleRelease --stacktrace | tee output.txt
#            echo "apk_path=$(find ${{ github.workspace }}/app/build/outputs/apk/release -name *.apk)" >> $GITHUB_ENV

      - name: Build UnSigned Release APK
        run: |
            ./gradlew assembleDebug 
            echo "apk_path=$(find ${{ github.workspace }}/app/build/outputs/apk/release -name *.apk)" >> $GITHUB_ENV

      - name: Display APK Path
        run: | 
          echo "APK Path: ${{ env.apk_path }}"

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: debug
          path: ${{ env.apk_path }}